### PR TITLE
Bundle size optimization

### PR DESCRIPTION
**Pull request by aga5tya**
This fixes investtools/extensible-duck#3. Brings in around 85% lesser bundle size

@akelmanson Kindly review :)

> Modified to use latest webpack and enable tree shaking.
> Makes use of lodash-webpack-plugin to cherry pick lodash methods to absolute need.
> Linted gulp file with prettier.

Before:
screen shot 2017-07-12 at 3 48 58 pm

After:
screen shot 2017-07-12 at 3 49 17 pm

### CODE REVIEW

**Comment by aga5tya** [comment]
CI is failing 
```
[BABEL] /home/travis/build/investtools/extensible-duck/src/extensible-duck.js: Unknown option: foreign.__esModule. Check out http://babeljs.io/docs/usage/options/ for more info
```
This shouldn't happen with babel version is bumped up to latest. Works on my local just fine. Need your help here @akelmanson

**Comment by akelmanson** [comment]
Hi there! Thank you for the contribution. It seems that bumping babel to latest is not an option. Please check out #2.

**Comment by aga5tya** [comment]
@akelmanson: Set the preset back to es2015. Works as expected and builds pass. Please review 👍

**Comment by akelmanson** [comment]
@aga5tya could you please adjust the indent to 2 spaces in order to let the diff tool show only the actual changes?

**Comment by aga5tya** [comment]
@akelmanson, Done 👍

**Comment by aga5tya** [comment]
@akelmanson Thanks for merging the PR :) Let me know once you push a version.

Also a badge would look nice in the Readme section. Its 3.4kb min & gzipped 🎉 
```
![](http://img.badgesize.io/investtools/extensible-duck/master/dist/extensible-duck.min.js?compression=gzip)
```

**Comment by akelmanson** [comment]
Done! v1.0.2

**Pull request merged**
